try {
    unbekannteFunktion();
} catch (e) {
    console.log(e.message);
}
